#!/bin/bash

servicename=${servicename:-nginx-ui}
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=${DAEMON:-/usr/local/bin/nginx-ui}
DAEMON_ARGS=${DAEMON_ARGS:--config /etc/nginx-ui/app.ini}
PIDFILE=${PIDFILE:-/var/run/nginx-ui.pid}

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start()
{
    start-stop-daemon --start -v --background --name nginx-ui --make-pidfile --pidfile $PIDFILE --exec "$DAEMON $DAEMON_ARGS"
    RETVAL="$?"
    return "$RETVAL"
}

do_stop()
{
    start-stop-daemon -v --stop  --retry=TERM/30/KILL/5 --oknodo --pidfile $PIDFILE
    RETVAL="$?"
    rm -f $PIDFILE
    return "$RETVAL"
}

case "$1" in
        start)
    do_start
        ;;
        stop)
    do_stop
        ;;
        restart)
    do_stop
    do_start
        ;;
        status)
    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
        *)
                echo "Usage: $servicename {start|stop|restart|status}"
                exit 1
        ;;
esac
