#!/bin/bash

servicename=${servicename:-nwaf_update}
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=${DAEMON:-/usr/share/nwaf/venv/bin/python3.9}
DAEMON_ARGS=${DAEMON_ARGS:-/usr/share/nwaf/rule-update.pyc}
PIDFILE=${PIDFILE:-/var/run/nwaf_update.pid}

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start()
{
    start-stop-daemon --start -v --background --name mla --make-pidfile --pidfile $PIDFILE --exec $DAEMON $DAEMON_ARGS
    RETVAL="$?"
    return "$RETVAL"
}

do_stop()
{
    start-stop-daemon -v --stop  --retry=TERM/30/KILL/5 --oknodo --pidfile $PIDFILE
    RETVAL="$?"
    pids=$(ps -Af | grep "nwaf/rule-update.pyc" | grep -v grep | awk '{print $2}')
    for pid in ${pids[@]}; do kill -9 $pid; done

    rm -f $PIDFILE
    return "$RETVAL"
}

case "$1" in
        start)
    do_start
        ;;
        stop)
    do_stop
        ;;
        restart)
    do_stop
    do_start
        ;;
        status)
    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
        *)
                echo "Usage: $servicename {start|stop|restart|status}"
                exit 1
        ;;
esac
